project_id = "gibdd-exam-simulator"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 500

[db]
major_version = 17

[auth]
enabled = true
enable_signup = true
enable_anonymous_sign_ins = true
site_url = "https://skeetels.github.io/GibddExamSimulator"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true

[auth.email]
enable_signup = false
enable_confirmations = true
double_confirm_changes = true

[functions.telegram-report]
verify_jwt = true

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-delivery-worker]
verify_jwt = false

[functions.device-api]
verify_jwt = false
